version: '3.7'

services:

  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_DB: retail
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - retail

volumes:
  postgres:

networks:
  retail:
    driver: bridge
